<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNYvrhRf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNYvrhRf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNYvrhRf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNYvrhRf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNYvrhRf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NYvrhRf',
    'container.build_id' => '11caf020',
    'container.build_time' => 1615817956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNYvrhRf');
