<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'newClient' => [[], ['_controller' => 'App\\Controller\\ClientController::client'], [], [['text', '/newClient']], [], []],
    'app_materiel_edit' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/materiel/edit']], [], []],
    'app_materiel_delete' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/materiel/delete']], [], []],
    'materiellist' => [[], ['_controller' => 'App\\Controller\\MaterielController::show'], [], [['text', '/materiellist']], [], []],
    'materiel' => [[], ['_controller' => 'App\\Controller\\MaterielController::new'], [], [['text', '/materiel']], [], []],
    'app_mon_edit' => [['id'], ['_controller' => 'App\\Controller\\MonController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/contact/edit']], [], []],
    'app_mon_delete' => [['id'], ['_controller' => 'App\\Controller\\MonController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/contact/delete']], [], []],
    'contactlist' => [[], ['_controller' => 'App\\Controller\\MonController::show'], [], [['text', '/contactlist']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\MonController::new'], [], [['text', '/contact']], [], []],
    'app_mon_navbar' => [[], ['_controller' => 'App\\Controller\\MonController::navbar'], [], [['text', '/navbar']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\MonController::home'], [], [['text', '/']], [], []],
    'a_propos' => [[], ['_controller' => 'App\\Controller\\MonController::about'], [], [['text', '/about']], [], []],
    'product' => [[], ['_controller' => 'App\\Controller\\MonController::produit'], [], [['text', '/product']], [], []],
    'services' => [[], ['_controller' => 'App\\Controller\\MonController::services'], [], [['text', '/services']], [], []],
    'newProduct' => [[], ['_controller' => 'App\\Controller\\ProductController::product'], [], [['text', '/newProduct']], [], []],
];
